version: '3.6'
services:
  node:
    container_name: api_twitter_node
    image: 'node:latest'
    working_dir: /home/node/app
    command:
        - "/bin/bash"
        - "-c"
        - "npm install && npm start" 
    volumes:
        - './src:/home/node/app'
    env_file: '.env'     
  
  web-nginx:
    build:
           context: ./nginx
    depends_on: 
        - node  
    working_dir: /etc/nginx/conf.d
    ports:
        - "3000:80"
        - "443:443"
    volumes:
        - "$PWD/nginx:/etc/nginx/conf.d"  
  mongo:
    container_name: api_twitter_mongo
    image: mongo
